### ISSUE TITLE
Consider switching FluentBundle to take Rc<FluentResource>

### ISSUE THREAD

**Issue by zbraniecki** [projectfluent/fluent-rs#103]
Currently, we create `FluentBundle` passing references to `FluentResource`. That requires a quite a bit of sophisticated life time hand holding. We could instead handle `Rc<FluentResource>` which would make lifetimes easier.

**Comment by chanks** [comment]
I'm glad to see this issue, I've been struggling with this myself. My code looks like:

```rust
pub fn bundles_by_locale() -> HashMap<String, FluentBundle<'static>> {
    let locales = get_available_locales().expect("Couldn't get list of existing locales!");
    let mut result = HashMap::new();

    for locale in locales {
        let file_name = format!("{}.ftl", locale);

        let source = read_localization_file(&file_name).expect("Failed to read file.");
        let resource = FluentResource::try_new(source).expect("Could not parse an FTL string.");

        let mut bundle: FluentBundle = FluentBundle::new(&[&locale]);

        bundle
            .add_resource(&resource)
            .expect("Failed to add FTL resources to the bundle.");

        result.insert(locale, bundle);
    }
    result
}
```

The compiler complains with `cannot return value referencing local variable 'resource'`. Is there an example somewhere of how to define lifetimes to handle a case like this?

**Comment by zbraniecki** [comment]
Please, take a look at `fluent-resmgr` and `fluent-fallback` tests and examples for how we suggest to handle lifetimes right now!

I understand that it's not ideal, but it likely is the optimal from the perf/mem perspective. I'll continue investigating but in the meantime, the examples from those two crates should help you - if you want your own resource manager, use just the `fluent-fallback`, but if you just want to load files, `fluent-resmgr` may be the easiest solution.

Let me know if that helps!

**Comment by zbraniecki** [comment]
@chanks - can you verify that the problem is fixed on master? `FluentBundle` now is a generic that can take ownership, reference or Rc/Arc.

**Comment by chanks** [comment]
Thanks @zbraniecki - I wound up solving this problem by setting up resources and bundles in their own lazy_static declarations, which has been working fine for me, and I'm not sure when I'll have time to try out this new API. I'm sure I'll get around to it at some point, but please don't wait on me for a release or anything :grimacing:

**Comment by zbraniecki** [comment]
Closing!
