### ISSUE TITLE
Consider switching FluentBundle to store Rc<FluentResource>

### ISSUE THREAD

**Issue by zbraniecki** [projectfluent/fluent-rs#111]
The current management of `FluentResource` and `FluentBundle` is likely optimally fast and memory safe, but hard to deal with in reality.

While working on an experiment to bring `FluentBundle` and `FluentResource` to Gecko via WebIDL, I once again ended up with an expectation to use `Rc`.

Sooo, how about if we switch to `Rc`? Suddenly, we don't need a fancy resource manager to store `FluentResource` objects, and we can freely feed resources to bundle. And if we need two bundles to use the same resource, we just feed them to `Rc`s!

Question 1: Is `Rc` limiting us in anything major? Since we're targeting `fluent-rs` to be a general use crate for localization, is there any common use case which would make `fluent-rs` unusable if we switched to `Rc`?

The challenge I encountered is that I'm not sure how can I hash references to particular `ast::Message` for quick retrieval in the `Rc` scenario.

In the current code I have (simplified):

```rust
struct FluentBundle<'bundle> {
    messages: HashMap<String, &'bundle ast::Message>,
}

impl FluentBundle {
    fn add_resource(&mut self, res: &FluentResource) {
        for msg in res.body {
            self.messages.insert(msg.id.name.to_string(), msg);
        }  
    }
}
```

now, in the `Rc` version I'd have sth like:

```rust
struct FluentBundle {
    resources: Vec<Rc<FluentResource>>,
    messages: HashMap<String, &'? ast::Message>,
}

impl FluentBundle {
    fn add_resource(&mut self, res: Rc<FluentResource>) {
        self.resources.push(res);
        ?? // how to hash references to ast::Message ?
    }
}
```

@Manishearth - can you advise on those two issues?

**Comment by Manishearth** [comment]
Yeah, I think it's not a big deal to use Rc here, you won't have many of these.

**Comment by Manishearth** [comment]
Just put `Rc`s in the `HashMap`.

**Comment by Pike** [comment]
The `Resource` would also hold `Rc`s to entries? Would that refcount on each `format`?

I guess the pseudo-pointer-arithmetics of hashing to an index tuple (resource index, message index) would be frowned upon?

**Comment by Manishearth** [comment]
Yeah i'd misunderstood the issue.

The OwningRef crate is what you're looking for, but that's also costly somewhat. The borrows may be the best solution here.

You can:

 - use `rental` to have the bundle borrow from its resources
 - create a custom unsafe abstraction for this
 - use owningref

**Comment by Manishearth** [comment]
You would have to replace the `Vec` with a `FrozenVec` to safely do anything with rental or unsafe here.

**Comment by zbraniecki** [comment]
I can also just make the hashmap store indexes of position of the `FluentResource` in the Vec and of the `Message` in its body. I'll start with that for simplicity.

**Comment by zbraniecki** [comment]
Initial benchmarks show no performance impact!

```
Zibis-MacBook-Pro:fluent-bundle (res-rc)$ cargo bench
   Compiling fluent-bundle v0.6.0 (/Users/zbraniecki/projects/fluent/fluent-rs/fluent-bundle)
    Finished release [optimized] target(s) in 3.48s
     Running /Users/zbraniecki/projects/fluent/fluent-rs/target/release/deps/fluent_bundle-bc86282321263cbe

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running /Users/zbraniecki/projects/fluent/fluent-rs/target/release/deps/resolver-84e6f1639e28e79a
Gnuplot not found, disabling plotting
resolve/"simple"        time:   [8.8936 us 8.9533 us 9.0190 us]                              
                        change: [-0.2071% +0.7415% +1.9130%] (p = 0.16 > 0.05)
                        No change in performance detected.
Found 6 outliers among 100 measurements (6.00%)
  3 (3.00%) high mild
  3 (3.00%) high severe
resolve/"preferences"   time:   [129.92 us 130.81 us 131.79 us]                                  
                        change: [-1.9776% -0.9997% +0.0259%] (p = 0.06 > 0.05)
                        No change in performance detected.
Found 8 outliers among 100 measurements (8.00%)
  6 (6.00%) high mild
  2 (2.00%) high severe
resolve/"menubar"       time:   [37.435 us 37.705 us 38.008 us]                               
                        change: [-0.6283% +0.5389% +1.6198%] (p = 0.35 > 0.05)
                        No change in performance detected.
Found 6 outliers among 100 measurements (6.00%)
  1 (1.00%) low mild
  5 (5.00%) high mild
resolve/"unescape"      time:   [2.0607 us 2.0726 us 2.0852 us]                                
                        change: [-1.0352% -0.1906% +0.6717%] (p = 0.66 > 0.05)
                        No change in performance detected.
Found 4 outliers among 100 measurements (4.00%)
  2 (2.00%) high mild
  2 (2.00%) high severe

Gnuplot not found, disabling plotting
```

**Comment by zbraniecki** [comment]
Hmm, @Manishearth  - should we use `Rc` or `Arc`?

Amethyst was once asking for Send+Sync - https://github.com/amethyst/amethyst/issues/1039#issuecomment-429874243

**Comment by Manishearth** [comment]
Arc makes sense since you're not cloning that often

**Comment by zbraniecki** [comment]
switched the PR to `Arc`

**Comment by stasm** [comment]
I'm not very fond of the idea to store message indices into ` FluentResource`. Perhaps `FluentResource` should be changed to store (and uniquely own) a hash map of message ids to `ast::Message`? `FluentBundle` could then retrieve a particular message by either iterating over all resources, or by storing a map of message ids to a `FluentResource` that has the message.

**Comment by zbraniecki** [comment]
> I'm not very fond of the idea to store message indices into FluentResource.

What makes you not fond of it?

**Comment by stasm** [comment]
We're building these abstractions to represent interesting data, but we end up with indices, which are completely disconnected from the data. It does remind me of pointer arithmetics that @Pike mentioned. I understand this is done for simplicity for now, and my suggestion may be a follow-up material.

**Comment by zbraniecki** [comment]
> I understand this is done for simplicity for now, and my suggestion may be a follow-up material.

My challenge is that it seems to me that anything else would be more costly and I fail to see any benefit of it.

I understand that indices feel "raw", but I'm not sure if "raw" is bad. It's a private "raw" that will be solely managed by `add_resource`/`remove_resource` and gives us lowest overhead.
Making `FluentResource` store a HashMap, as you suggested, would be more costly for no added benefit (and a bit more complicated lifetimes).

**Comment by zbraniecki** [comment]
Closing in favor of #113.
