### ISSUE TITLE
Consider switching format_pattern to (String, Vec<Error>)

### ISSUE THREAD

**Issue by zbraniecki** [projectfluent/fluent-rs#125]
Are you still planning to change the return value of `format_pattern` to `(String, Option<Vec<Error>>)`?

_Originally posted by @stasm in https://github.com/projectfluent/fluent-rs/pull/120_

**Comment by stasm** [comment]
Related: we could also consider removing `errors` from the signature of `format_pattern`.

**Comment by zbraniecki** [comment]
> Related: we could also consider removing errors from the signature of format_pattern.

What do you mean by that?

**Comment by stasm** [comment]
Since errors would be _returned_ from `format_pattern` (wrapped in an `Option`), I think there's little use left for the third argument to `format_pattern`. We could thus change:

```rust
let value = bundle.format_pattern(&pattern, Some(&args), &mut errors);
```

to:

```rust
let (value, maybe_errors) = bundle.format_pattern(&pattern, Some(&args));
```

**Comment by zbraniecki** [comment]
Ah yes, that was my thinking as well!

**Comment by zbraniecki** [comment]
This gets moved to 0.8.

**Comment by zbraniecki** [comment]
I actually went the other direction - I now accept a `&Vec` of Errors that `FluentBundle` populates. I think this is a better approach as it allows the user to decide how to handle errors (per format, or per list of formats) without any additional allocations.

I may also switch to allow *not* to pass the errors in which case errors won't be populated at all.

**Comment by zbraniecki** [comment]
I'm going to close it. I believe that errors vec should not be allocated as part of the return value, and instead should be passed to the call in some higher level code that will handle the outcome of errors (fallbacks, reporting etc.).
