### ISSUE TITLE
Build is broken due to missing intl_pluralrules version

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent-rs#129]
https://github.com/projectfluent/fluent-rs/commit/b00eb34a6b775eff6d63441a05ea9ef5a097793a updated the dependency on `intl_pluralrules` to 1.1.0 which has been since yanked from crates.io.

The Travis build for this commit to master succeeded, because `intl_pluralrules` was still available. I restarted one job at https://travis-ci.org/projectfluent/fluent-rs/builds/563330820 and you can see that it's now failing.

Normally, yanking is not a problem for existing dependencies, as long as `Cargo.lock` is kept up to date and is commited too. But https://github.com/projectfluent/fluent-rs/commit/b00eb34a6b775eff6d63441a05ea9ef5a097793a only updated `Cargo.toml`.

**Comment by zbraniecki** [comment]
yep, fixed.
