### ISSUE TITLE
fluent_args documentation is unclear

### ISSUE THREAD

**Issue by cmyr** [projectfluent/fluent-rs#135]
The code in the docs for `fluent_args!` won't compile as written.

The following program, with `fluent = "0.7"` in the manifest:

```rust
use fluent::fluent_args;

fn main() {
    let mut args = fluent_args![
        "name" => "John",
        "emailCount" => 5
    ];
}
```

produces the error,
```
error[E0433]: failed to resolve: could not find `fluent_bundle` in `{{root}}`
 --> src/main.rs:6:16
  |
6 |   let mut args = fluent_args![
  |  ________________^
7 | |     "name" => "John",
8 | |     "emailCount" => 5
9 | | ];
  | |_^ could not find `fluent_bundle` in `{{root}}`
  |
  = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

This is resolved if I explicitly add `fluent-bundle` to my manifest, but this is confusing, since the macro is only exposed in the `fluent` crate, and it would be nice if I only needed to provide the one dependency.

**Comment by Pike** [comment]
That's #132, right? That's waiting to be released, though.

**Comment by zbraniecki** [comment]
yep, will release 0.7.1 tomorrow!

**Comment by cmyr** [comment]
Cool, thanks!
