### ISSUE TITLE
Consider PGO

### ISSUE THREAD

**Issue by zbraniecki** [projectfluent/fluent-rs#136]
Now that PGO landed in stable, I think it may be generally useful, especially to speed up the parser.

**Comment by alerque** [comment]
I think using PGO makes perfect sense, but this is a downstream problem. This project doesn't distribute binaries, and the optimizations provided by PGO need to be applied at compile and linking time and applied to final binaries. The profiling likewise will come up with different results based on the project context where it is run. Hence any PGO that can be applied necessarily will be done by downstream projects on their apps that use these crates, not in these crates themselves.

To my knowledge there isn't much in the way of feedback from the PGO generated profiles that could be used to change the underlying code. If I'm wrong about that feel free to correct me and re-open. To the best of my knowledge any benchmarking and profiling that can be done that would help optimize the *code* is unrelated to PGO.
