### ISSUE TITLE
`Localization::format_value` takes `&mut self`

### ISSUE THREAD

**Issue by Follpvosten** [projectfluent/fluent-rs#147]
`fluent_fallback::Localization::format_value` takes self by mutable reference where I don't think it is necessary (when I remove the `mut`, it still compiles).

I'm not sure if that's wrong or intentional; in case it shouldn't be like that, should I open a PR?

**Comment by zbraniecki** [comment]
Thank you for reporting!
Fixed in https://github.com/projectfluent/fluent-rs/commit/4123cf37f9b531d3191d52b08a1e48785dccb00a
