### ISSUE TITLE
Webassembly support

### ISSUE THREAD

**Issue by dimiro1** [projectfluent/fluent-rs#151]
Is it feasible to compile down this project as a web assembly module to use for example in Go projects using https://github.com/perlin-network/life or https://github.com/wasmerio/go-ext-wasm ?

**Comment by anlumo** [comment]
We're using it in a wasm project without any changes.

**Comment by dimiro1** [comment]
Cool @anlumo did you created the bindings yourself or are you using interface types[1]?  Can you share your setup?

[1] https://github.com/WebAssembly/interface-types/blob/master/proposals/interface-types/Explainer.md

**Comment by zbraniecki** [comment]
I'm going to close it, please, reopen if you have more direct questions or reaquests for the project (also, would love PRs with documentation!)

**Comment by dakom** [comment]
I see this is a fairly old issue - but I'm curious, roughly how much weight does fluent add (esp relevant for wasm targets)?
