### ISSUE TITLE
Improve the documentation on `FluentBundle::format_pattern`

### ISSUE THREAD

**Issue by XAMPPRocky** [projectfluent/fluent-rs#156]
Hello, I was updating some dependencies and between version `0.5` -> `0.9`, `FluentBundle::format` was removed in place of `FluentBundle::format_pattern`, however there is no documentation on how to use `format_pattern`. And there is no documentation how to construct a `fluent_syntax::ast::Pattern` to be able to pass to the function. I would really appreciate if there was some end user documentation on how to use this function.

**Comment by zbraniecki** [comment]
Hi!

I recognize that the current documentation is suboptimal. I'm sorry for that, I've been focused on completing the feature set first.

Please, consult the `fluent_bundle/examples/` directory for examples on how to use the new API.

Let me know if you find the answers there! `hello.rs` should be a good start :)

**Comment by zbraniecki** [comment]
I will keep this open with a plan to improve the docs on `format_pattern` to explain where the `Pattern` should come from.

**Comment by zbraniecki** [comment]
I landed a bunch of docs for `get_message`, `format_pattern` and `write_pattern` with examples.
