### ISSUE TITLE
Consider rewriting the parser to make it copy-free

### ISSUE THREAD

**Issue by zbraniecki** [projectfluent/fluent-rs#16]
At the moment the parser is copying some parts of the slice while creating the AST.

Most Rust parsers I can find in the wild rather rely on building AST that stores slices and aim for zero-copy mode.
Last example: https://github.com/viperscape/lichen/blob/master/src/parse.rs

I think we could do this here and it would probably benefit performance and memory. The cost is that if you want to modify the AST you'll have to copy it, but that seems to be a reasonable cost.
Most use cases only need to read the AST from what I know.

**Comment by Cyres** [comment]
Basically every `String` could be replaced with `&'ctx str` as far as i inspected the source code.

**Comment by zbraniecki** [comment]
Fixed by https://github.com/projectfluent/fluent-rs/pull/76
