### ISSUE TITLE
Example code incompatable with unic_locale 0.9.0

### ISSUE THREAD

**Issue by alerque** [projectfluent/fluent-rs#178]
I just tried to update a project that uses *fluent_langneg* to *unic_locale* 0.9.0 and ran into trouble. I'm not sure which side is to blame, but it seems like if the upstream change was intentional the example code here should be updated to work.

See also https://github.com/zbraniecki/unic-locale/issues/59

**Comment by zbraniecki** [comment]
Hi, I just updated the whole toolchain. Can you try against the current latest?

**Comment by alerque** [comment]
That did the trick, thanks!
