### ISSUE TITLE
Change `FluentArgs` key type to `String`.

### ISSUE THREAD

**Issue by XAMPPRocky** [projectfluent/fluent-rs#179]
Currently `FluentArgs` is a `HashMap<&str, FluentValue>`, which is okay when you're using str literals as keys, however when you're constructing your map dynamically you don't have a `HashMap<&str, V>` only a `String`. Currently you have to construct a new HashMap that takes the key by reference and clones the `FluentValue`. It would easier for users and more appropriate if it was `HashMap<String, FluentValue>`.

```rust
// Current
pub type FluentArgs<'args> = HashMap<&'args str, FluentValue<'args>>;
// Proposed
pub type FluentArgs<'args> = HashMap<String, FluentValue<'args>>;
```

**Comment by zbraniecki** [comment]
Hmm, I'm torn on this. I'm wondering if there's a way to handle both scenarios without having to give up on the former.

**Comment by zbraniecki** [comment]
See #94 for the motivation for current design.

**Comment by XAMPPRocky** [comment]
@zbraniecki AFAIK the best way to handle this would be Generic Associated Types but that isn't currently available. I don't know what the best workaround would be but with the current API I can actually be allocating more since I have to construct a new map each key by reference and each value by value versus just allocating a string each time. If I wanted to reduce allocations with Fluent I could do that on the user side with memoization for the argument map but I actually can't use memoization on `FluentArgs` currently currently because memoization requires owning the data in some way.

**Comment by zbraniecki** [comment]
@XAMPPRocky can you check if the current master branch solved it? I switched `FluentArgs` to accept `Cow` which hopefully solves it.

**Comment by XAMPPRocky** [comment]
Yeah `Cow` works for me. Thanks for working on this!
