### ISSUE TITLE
Unable to parse multiline messages with a selector in CRLF formatted fluent file on Windows

### ISSUE THREAD

**Issue by kellpossible** [projectfluent/fluent-rs#191]
I'm currently working on producing a minimal example that reproduces this issue, hopefully ready by today. It's a very strange issue! Just saving to LF fixes the problem. It's certainly possible that it's something wrong I'm doing on my end, perhaps while reading the file, if so, I'll close the issue.

**Comment by kellpossible** [comment]
Here is the reproduction: https://github.com/kellpossible/fluent-multiline-bug
As it happens the same issue occurs on Linux.

**Comment by zbraniecki** [comment]
Hi! I tried to reproduce it against current `master` branch and couldn't! Can you verify that this is fixed?

**Comment by kellpossible** [comment]
@zbraniecki awesome thanks a lot! The problem appears to be fixed on master :slightly_smiling_face:  https://github.com/kellpossible/fluent-multiline-bug/tree/fixed-on-master Some small breaking changes with the ast, but I guess that's to be expected when playing with internals. Looking forward to the next release.

**Comment by zbraniecki** [comment]
great!

**Comment by zbraniecki** [comment]
I'll close it as resolved in 0.13

**Comment by kellpossible** [comment]
Just a heads up someone reported a very similar issue https://github.com/kellpossible/cargo-i18n/issues/57 I'll try to make a minimal reproduction again.

**Comment by kellpossible** [comment]
I've reported this as a new issue https://github.com/projectfluent/fluent-rs/issues/213
