### ISSUE TITLE
Unable to parse multiline messages formatted with CRLF with breaks that don't match the indentation of the rest of the message

### ISSUE THREAD

**Issue by kellpossible** [projectfluent/fluent-rs#213]
When I have a message like:

```txt
multiline-message = 
    This is a multiline message 1.

    This is a multiline message 2.
```

Fluent successfully parses when the file is formatted with LF, but has a parse error when the file is formatted with CRLF.

However if the gap between the lines contains indentation matching the other lines, then it successfully parses with both LF and CRLF.

```txt
multiline-message = 
    This is a multiline message 1.
    
    This is a multiline message 2.
```

Editors often automatically remove this indentation, or don't place it in the first place.

**Comment by kellpossible** [comment]
I have created a minimal reproduction of the issue in the [`multiline-break-indentation-bug` branch of this repo](https://github.com/kellpossible/fluent-multiline-bug/tree/multiline-break-indentation-bug)

**Comment by Pike** [comment]
Fly-by note, the ´crlf´ test is disabled, https://github.com/projectfluent/fluent-rs/blob/cd8d6c4e7a20ff69762ff86c7a169df790d50ddd/fluent-syntax/tests/parser_fixtures.rs#L21-L23

Did you test your example on other implementations by any chance?

**Comment by Pike** [comment]
Also, can you set `.gitattributes` on your example repo to ensure that we all look at the same line endings?

**Comment by kellpossible** [comment]
> Also, can you set `.gitattributes` on your example repo to ensure that we all look at the same line endings?

I'm not familiar with `.gitattributes` but I gave it a try, please let me know if you think it's correct

**Comment by Pike** [comment]
Yes, thanks. Sadly not through the gh UI, but when cloning it does.

Also tested the python ipml just now, that parses OK

**Comment by zbraniecki** [comment]
This should be now fixed by https://github.com/projectfluent/fluent-rs/commit/0195099c8a71dcfa2acd05578e94ed6d1203549a - can someone verify?

**Comment by zbraniecki** [comment]
Closing. Reopen if needed.
