### ISSUE TITLE
Coveralls upload is failing

### ISSUE THREAD

**Issue by mathjazz** [projectfluent/fluent-rs#232]
Checks are often failing at the "Coveralls upload" step:
https://github.com/projectfluent/fluent-rs/runs/3186541921
https://github.com/projectfluent/fluent-rs/runs/3124033996
https://github.com/projectfluent/fluent-rs/runs/3019102558

The failure seems unrelated to the patch.

Here's the error output:
```
Run coverallsapp/github-action@master
  with:
    github-token: ***
    path-to-lcov: coverage.lcov
    coveralls-endpoint: https://coveralls.io
Using lcov file: coverage.lcov
Error:  "2021-07-28T22:16:14.684Z"  'error from lcovParse: ' 'Failed to parse string'
Error:  "2021-07-28T22:16:14.686Z"  'input: ' 'TN:\n'
Error:  "2021-07-28T22:16:14.686Z"  'error from convertLcovToCoveralls'
Error: Failed to parse string
```

**Comment by alerque** [comment]
The runs you linked to are long out of date and logs are not available to me, but I've been watching CI runs in the past few days as we've merged a bunch of stuff and it seem sike we're getting coverage updates on a pretty reliable basis. If you (or anyone) spots a recurrence of this problems drop a commend and we'll re-evaluate, but it seems to me this might be a non-issue now.
