### ISSUE TITLE
Concurrent FluentBundle not accessible

### ISSUE THREAD

**Issue by FKanzler** [projectfluent/fluent-rs#238]
Hello,

unfortunately I am not able to figure out how to access the concurrent specialization of FluentBundle.

In the documentation it says:
> ### Concurrency
>---
> As you may have noticed, fluent_bundle::FluentBundle is a specialization of fluent_bundle::bundle::FluentBundle which works with an IntlLangMemoizer over RefCell. In scenarios where the memoizer must work concurrently, there’s an implementation of IntlLangMemoizer that uses Mutex and there’s FluentBundle::new_concurrent which works with that.

Simplified code:
```rust
use fluent_bundle::{FluentResource, FluentBundle}; //version: 0.15.1

let mut bundle = FluentBundle::new_concurrent(vec![langid!("en-US")]);
```
 
 Compiler error:
```
error[E0599]: no function or associated item named `new_concurrent` found for struct `FluentBundle<_, intl_memoizer::IntlLangMemoizer>` in the current scope
   --> libs\translate\src\lib.rs:139:52
    |
139 |                     let mut bundle = FluentBundle::new_concurrent(vec![langid!("en-US")]);
    |                                                    ^^^^^^^^^^^^^^ function or associated item not found in `FluentBundle<_, intl_memoizer::IntlLangMemoizer>`

error: aborting due to previous error
```

Is there something I'm missing here? How could this be made to work?

**Comment by gregtatum** [comment]
The work here is to re-export the `new_concurrent` as suggested above. The IntlLangMemoizer is covered by #256.

**Comment by adriantombu** [comment]
@gregtatum From what I understand the problem comes from [here](https://github.com/projectfluent/fluent-rs/blob/main/fluent-bundle/src/lib.rs#L122) where we redefine `FluentBundle` as

```pub type FluentBundle<R> = bundle::FluentBundle<R, intl_memoizer::IntlLangMemoizer>```

thus prohibiting any use of the `new_concurrent` function with a `use fluent_bundle::{FluentBundle}` import.

---

A simple solution can be to create the following type

```pub type FluentBundleConcurrent<R> = concurrent::FluentBundle<R, concurrent::IntlLangMemoizer>;```

to allow `use fluent_bundle::{FluentBundleConcurrent}`. What are your thoughts on this?

**Comment by alerque** [comment]
As far as I understand, this is and was fixed already. There is a comment in #300 about a regression, but looking at the code right now I don't see it. You should be able to use `concurrent::FluentBundle` for your type and `FluentBundle::new_concurrent()` as a constructor.

If I'm missing something and this is not actually viable, please by all means do comment back here and I'll re-open and re-evaluate what is going on.
