### ISSUE TITLE
Rustdoc links have incorrect syntax

### ISSUE THREAD

**Issue by SOF3** [projectfluent/fluent-rs#239]
Rustdoc intra-links should use [\`foo\`][bar] instead of \[\`foo\`](bar) if it references a code item.

https://doc.rust-lang.org/rustdoc/linking-to-items-by-name.html

**Comment by gregtatum** [comment]
I don't think this is accurate? Nothing in the linked doc suggests this is a requirement. If I'm wrong please show me where I'm missing it.

**Comment by SOF3** [comment]
not sure how come I wrote that one year ago or where I found broken links, but you're right, parentheses are correct.

**Comment by gregtatum** [comment]
There are definitely some broken links, as they are not being linted for.
