### ISSUE TITLE
Call expressions

### ISSUE THREAD

**Issue by zbraniecki** [projectfluent/fluent-rs#24]
We need to add CallExpressions support to our resolver and some built-in functions for things like date formatting (it's ok if we mock them for now)

**Comment by stasm** [comment]
Is this a dupe of #19? Or should we keep #19 about supporting `NUMBER()` without any arguments and make this issue about adding arguments and other builtins?

**Comment by zbraniecki** [comment]
No, let's stick to #19 for everything.
