### ISSUE TITLE
Support custom functions in MessageContext

### ISSUE THREAD

**Issue by zbraniecki** [projectfluent/fluent-rs#25]
We want to support passing arbitrary generic functions as arguments to MessageContext constructor to allow developers to provide builtins into localization contexts.

**Comment by JohnDoneth** [comment]
Close due to #50?

**Comment by zbraniecki** [comment]
Yep! :) Thanks again!

**Comment by stasm** [comment]
Nice, that was a big one. It feels great to be able to cross it off the list!
