### ISSUE TITLE
Debug windows binaries crashes on Windows and Wine

### ISSUE THREAD

**Issue by qarmin** [projectfluent/fluent-rs#250]
When I compiled my app on Linux(both Debug and Release) or Windows(only Release), then everything works fine.
But when I started to use debug Windows builds(without any code change, except changing windows build to console), then I start to have this crashes when starting app(even with RUST_BACKTRACE=full don't show more detailed backtrace)

This is reopened issue  #249

Minimal project - https://github.com/qarmin/czkawka/tree/test_crash
Binaries not stripped(release - no crash, debug crash) - https://github.com/qarmin/czkawka/actions/runs/1662075703

**Comment by dvc94ch** [comment]
the problem is almost certainly with i18n-embed or your usage of it.

**Comment by kellpossible** [comment]
@dvc94ch it seems likely

**Comment by gregtatum** [comment]
This doesn't appear to be a fluent-rs issue, so I'm going to go ahead and close.
