### ISSUE TITLE
Documentation examples shouldn't use untranslated `expect`

### ISSUE THREAD

**Issue by clarfonthey** [projectfluent/fluent-rs#255]
This seems like a no-brainer to me.

Unless there's a failure to load localisation data in the beginning, every error returned should be localisable.

This is a pretty hard problem to solve, but one I think is worth solving.

**Comment by gregtatum** [comment]
I don't know that I agree with this. We use fluent-rs inside of Firefox, and these type of errors are only surfaced in the developer tools, not to our general population of multilingual users. The examples are mostly for showing how things can work, and are not complete localized UI.

Feel free to comment with specific examples where I am wrong here.
