### ISSUE TITLE
ResourceManager::get_resource panics rather than returning a result

### ISSUE THREAD

**Issue by gregtatum** [projectfluent/fluent-rs#278]
This API should let the consumer decide what to do when a resource can't be retrieved. Currently it panics with an `unwrap`.

https://github.com/projectfluent/fluent-rs/blob/9e62af6f18f5efed4ad8faaca2c6c0ceb14d5bde/fluent-resmgr/src/resource_manager.rs#L38

**Comment by adriantombu** [comment]
I can have a look at that 👀

**Comment by gregtatum** [comment]
Thanks! I'll assign it to you.

**Comment by gregtatum** [comment]
Oh, and just be aware I'm documenting around this area, so there might be some short-term merge conflicts.
