### ISSUE TITLE
Please dual-license

### ISSUE THREAD

**Issue by est31** [projectfluent/fluent-rs#31]
The gold standard for Rust projects is to dual license them under the Apache license and MIT. Most Rust crates are licensed that way. The Apache license gives users better patent protection, while the MIT is compatible to (L)GPL version 2 only projects. It would be nice if you would switch the license to dual license. The earlier the easier it is :).

Thanks!

**Comment by zbraniecki** [comment]
That sounds good to me! @stasm ?

**Comment by est31** [comment]
I see three contributors to the repo:

@zbraniecki 
@stasm 
@nvzqz

**Comment by nvzqz** [comment]
Sounds good to me :+1:

**Comment by stasm** [comment]
I'm personally fine with dual-licensing, but we should check with the [Licensing Team](https://www.mozilla.org/en-US/MPL/license-policy/). My understanding is that it should be OK. I filed [bug 1408992](https://bugzilla.mozilla.org/show_bug.cgi?id=1408992) to make sure.

**Comment by stasm** [comment]
We've got a green light. I submitted #34.

**Comment by stasm** [comment]
Thanks, everyone. We are officially dual-licensed now.
