### ISSUE TITLE
Which data providers Fluent crates use?

### ISSUE THREAD

**Issue by hydroper** [projectfluent/fluent-rs#314]
I think `fluent` relies on `icu`. Several of their constructors require a data provider. Do you simply use `icu_testdata` or have you passed through the [data management process](https://github.com/unicode-org/icu4x/blob/main/docs/tutorials/data_management.md)? If so, how can I reuse it? Or am I wrong about the use of `icu`? I'm asking because it could be an indirect dependency too.

Note, I think this because:

> What makes you think so?
>> @zbraniecki The built-in functions: https://projectfluent.org/fluent/guide/functions.html Inclusively it implements something like [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat).

**Comment by zbraniecki** [comment]
> I think fluent relies on icu.

What makes you think so?

**Comment by hydroper** [comment]
@zbraniecki The built-in functions: https://projectfluent.org/fluent/guide/functions.html Inclusively it implements something like [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat).

**Comment by alerque** [comment]
The build in functions you are referencing from the guide are not (to date) even implemented at all in the fluent-rs series of crates. There is current work in progress both and some discussion about specifics that you could jump into if you are interested. See #353 for the `NUMBER()` builtin and #181 for `DATETIME()`. Also note #269 where this is discussion and action towards using icu4x.
