### ISSUE TITLE
Add a lazy cache for Intl objects on MessageContext

### ISSUE THREAD

**Issue by zbraniecki** [projectfluent/fluent-rs#32]
Now that we have a proper `PluralRules` object, we should cache it on `MessageContext`.

**Comment by zbraniecki** [comment]
Ehh, this ends up being a very non trivial task.

I spent way too much time today on #rust trying to understand the limitations. It boils down to  -  it's not easy/possible to have a single cache for different types. If all our formatters had the same set of methods, we could do this with `impl Trait` and `trait object`.
But in the world where we have `PluralRules.select` and `DateTimeFormat.format`, it's very hard.

It is possible to use an enum here, in a `closed` model which will not allow third-party devs to add their own formatters (or at least, they wont be cached).

Unfortunately, that requires us to change the mutability of `ctx` and `env` in resolver, because now any call can trigger adding an object to cache, so you have to pass `mut env` all around.

@stasm - would you be interested in taking a look at this? Maybe you'll come up with some better model for this problem, because I feel like I'm out of ideas :(

**Comment by stasm** [comment]
We'll need some kind of mutability for `env` (via `mut` or `RefCell` maybe?) for #21, too. I'll first look into #21 and perhaps it will give us some ideas for this issue.

**Comment by mmstick** [comment]
What needs to be cached, exactly?

**Comment by zbraniecki** [comment]
nothing yet for we don't have any intl formatters. It's likely going to be delayed till later.

We're about to switch fluent to use https://github.com/unclenachoduh/pluralrules which will be the first intl formatter and it will not require any caching for now.

**Comment by zbraniecki** [comment]
but once we get intl date time formatting and number formatting we'll likely want to cache the instantiated structures.

**Comment by zbraniecki** [comment]
I was able to fix it trivially for now in https://github.com/projectfluent/fluent-rs/commit/7b0cd65c77b6011db9f2844996795b77f5f59bf5
