### ISSUE TITLE
Switching windows process/thread ui languages

### ISSUE THREAD

**Issue by crlf0710** [projectfluent/fluent-rs#322]
I'm trying to find a way to set either windows thread ui language(https://learn.microsoft.com/en-us/windows/win32/api/winnls/nf-winnls-setthreaduilanguage) or process prefered ui languages(https://learn.microsoft.com/en-us/windows/win32/api/winnls/nf-winnls-getprocesspreferreduilanguages, >= windows 7) according to what fluent decides to use from bundle. I wonder if this functionality could/should be part of fluent itself? Thanks!

**Comment by zbraniecki** [comment]
Hi @crlf0710 - FluentBundle is in a given locale. You can perform a locale negotiation between requested and available locales to select the best bundle. You can look into `fluent_fallback` for inspiration.

**Comment by crlf0710** [comment]
Thanks
