### ISSUE TITLE
Behaviour of FluentArgs::set is misleading

### ISSUE THREAD

**Issue by miam-miam** [projectfluent/fluent-rs#336]
`FluentArgs::set` does not currently replace arguments in the latest version of fluent-bundle (v0.15.2)

The PR that fixes this issue (https://github.com/projectfluent/fluent-rs/pull/271) was merged Oct 27 2022.

As such the issue is fixed using the main branch of this repository but unfortunately this is not the case for crates.io users.

It may be worth considering doing a release for `fluent-bundle` so that this change is available to users on crates.io.

**Comment by alerque** [comment]
The latest releases of these crates (safe-harbor) ones have all the work that was sitting around unreleased in Git HEAD for the last couple years up until a couple days ago when we started working through the backlog.
