### ISSUE TITLE
What would it take to support stable Rust?

### ISSUE THREAD

**Issue by emk** [projectfluent/fluent-rs#42]
Hello! `fluent` looks like a really amazing library, and I'd love to use it to localize the open source Rust [`substudy` application](http://www.randomhacks.net/substudy/). Unfortunately, `substudy` needs to be able to build under stable Rust (to make it easier for people to install it), and both `fluent` and `fluent-locale` use unstable Rust features for things like `box_patterns`.

Is there any plan to produce a version of `fluent` that is compatible with stable Rust? I'd love to be able to use it at some point. And if so, would you be interested in a PR that made it work?

**Comment by zbraniecki** [comment]
`fluent-rs` 0.2 has been released and it support stable!

**Comment by emk** [comment]
Thank you! I look forward to using this in a bunch of projects!
