### ISSUE TITLE
Design an AST for fluent-rs

### ISSUE THREAD

**Issue by zbraniecki** [projectfluent/fluent-rs#5]
Let's start an issue to design how we want our AST to look like.

**Comment by zbraniecki** [comment]
@stasm proposal is:
```
struct Message {
    id: String,
    value: Option<Expression>,
    traits: Option<Vec<Member>>,
}

struct Member {
    key: String,
    value: Expression,
    default: bool,
}

enum Expression {
    TextElement(String),
    MessageReference(String),
    ExternalArgument(String),
    SelectExpression {
        selector: Expression,
        variants: Vec<Member>
    },
    Pattern {
        elements: Vec<Expression>,
    },
    // etc.
}
```

**Comment by zbraniecki** [comment]
My proposal is:

```rust
struct Resource {
  body: Vec<Entry>,
  comment: Option<Comment>
}

struct Message {
  id: Identifier,
  value: Option<Pattern>,
  traits: Option<Vec<Member>>,
  comment: Option<Comment>
}

struct Comment {
  body: String
}

struct Section {
  key: Key,
  body: Vec<Entry>,
  comment: Option<Comment>
}

enum Entry {
  Message(Message),
  Comment(Comment),
  Section(Section),
  JunkEntry(JunkEntry)
}

struct Identifier {
  name: String,
}

struct Key {
  name: String
}

struct Number {
  value: String
}

struct Keyword {
  ns: Option<String>,
  name: Key
}

struct Pattern {
  elements: Vec<PatternElement>,
  quoted: bool
}

enum PatternElement {
  Text(String),
  Placeable {
    expressions: Vec<Expression>
  }
}

struct MemberKey {
  Keyword(Keyword),
  Number(Number)
}

struct Member {
  key: MemberKey,
  value: Pattern,
  default: bool,
}

pub enum Expression {
  ExternalArgument {
    id: Identifier
  },
  EntityReference {
    id: Identifier
  },
  FunctionReference {
    id: Identifier
  },
  Number(Number),
  CallExpression {
    callee: Box<Expression>,
    args: Vec<Expression>
  },
  SelectExpression {
    expression: Box<Expression>,
    variants: Vec<Member> 
  },
  KeyValueArgument {
    name: String,
    value: Box<Expression>
  },
  MemberExpression {
    object: Box<Expression>,
    keyword: MemberKey,
  }
}

struct JunkEntry {
  content: String,
}
```

**Comment by zbraniecki** [comment]
Several notes about my approach:

1. Struct have named fields, which also makes it easier to add "pos" field for position.
2. Expressions are only things that can be inside placeables. Every other element is a standalone struct
3. It still doesn't separate "simple" strings that are kvp values.
4. It would be very easy to add a simple regex to limit every String in this AST (which I'd consider doing)

**Comment by zbraniecki** [comment]
I think one thing we should take into account, and it may be fragile until we actually write it, is that I believe that this AST should be serializable with minimal changes in the parser/serialize cycle.

I think I'm ok with not storing white spaces in it, and serialize to "normalized" FTL (so kind of `cargo fmt` style), but I'd like to make sure that we preserve everything that we want to contain in the serialized result.

**Comment by stasm** [comment]
I was trying to design something very simple to support the goal of creating an MVP. I didn't realize you already did the work of designing the full thing!  :)

You proposal looks good to me.  I'll think about it a bit more today.  For now, I have a few questions:

 - Should we first follow through with the syntax changes discussed in tools-l10n?
 - Your `Expression` is missing `Pattern`. Is this intentional?
 - What is the purpose of `Box<Expression>`?

Also, while I think things like adding positions or validating regex are okay to consider, let's focus on the MVP for now.

**Comment by zbraniecki** [comment]
We held a call to decide on this and decided to go with my AST proposal.

Answers to questions asked by stas:

> Should we first follow through with the syntax changes discussed in tools-l10n?

No, we'll adapt to changes as we go.

>  Your Expression is missing Pattern. Is this intentional?

Yes, we'll narrow down what AST allows for now. We can always extend later.
Another example I just noticed and landed is that CallExpression only takes Identifier as callee (forbidding things like `2()`, `$foo()` and `foo()()`)

>   What is the purpose of Box<Expression>?

We'll have to box expressions in expressions because rust forbids them directly.
