### ISSUE TITLE
"www" in project description's URL leads to an invalid-certificate page

### ISSUE THREAD

**Issue by xmo-odoo** [projectfluent/fluent-rs#54]
Open "https://projectfluent.org" from projectfluent/fluent => home page of the project
Open "https://www.projectfluent.org" from projectfluent/fluent-rs => big "this connection is not private" warning from my browser

**Comment by stasm** [comment]
Thanks, I changed it to `https://projectfluent.org`, sans `www`. Last time I tried, I wasn't able to set up the `www` subdomain; see https://github.com/projectfluent/projectfluent.github.io/issues/17#issuecomment-387029670.
