### ISSUE TITLE
MessageContext.add_messages should not fail

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent-rs#62]
I noticed that #55 changed the signature of `MessageContext.add_messages` to `-> Result<(), FluentError>`. 

https://github.com/projectfluent/fluent-rs/blob/2d9ddb08bf78d5116c5372fe4929094a70816209/fluent/src/context.rs#L162-L169

I don't think this is right. The Fluent philosophy is to be tolerant of errors found in localization resources. If the localizer happens to duplicate a message, `MessageContext` should not reject to whole resource.

I noticed this thanks to `cargo test` reporting a lot of warnings about an unused `Result` from `add_messages`. If we end up keeping the `Result`, we should at least fix the warning.

**Comment by zbraniecki** [comment]
This has been fixed by https://github.com/projectfluent/fluent-rs/commit/d2d99923b5ec47d3d51d6292147b7809b1413357 - we now collect errors but continue adding messages.
