### ISSUE TITLE
Decouple locales lifetime from bundle

### ISSUE THREAD

**Issue by markpritchard** [projectfluent/fluent-rs#69]
Hi,

We are exploring using Rust to accelerate our Ruby app (internationalisation shows up as a bottleneck in profiles) and came across fluent-rs.

Thanks very much for creating and maintaining the library - it looks like a perfect fit for our use case.

As a disclaimer, I'm quite new to Rust so may have misunderstood this, but we ran into a problem with dynamically constructing `FluentBundle` instances and storing them in a map (e.g. keyed by a locale string we receive in a browser header).

The issue appeared to be that the `locales` input parameter to `FluentBundle::new` is tagged with the same lifetime as the bundle itself. #68 adds an explicit, separate lifetime to the `locales` parameter. 

Let me know if there are any issues with this PR (its my first one), and I'll be happy to address them.

Cheers,

Mark

**Comment by kirhgoff** [comment]
👍

**Comment by kirhgoff** [comment]
Here is the example that reproduces the problem, it fails with compilation error: https://github.com/kirhgoff/fluent-rs-lifetime-issue

**Comment by zbraniecki** [comment]
Thank you for your contribution! Merged the patch.
