### ISSUE TITLE
Can't publish to creates.io

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent-rs#7]
```
$ cargo publish --dry-run
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: all dependencies must come from the same source.
dependency `itertools` comes from https://github.com/bluss/rust-itertools instead
```

**Comment by zbraniecki** [comment]
We rely on a feature that has been added (at my request) in an unreleased version of itertools - https://github.com/bluss/rust-itertools/issues/180

Once itertools release, we can switch to it. I hope it'll happen before we're ready :)

**Comment by stasm** [comment]
This was unblocked by #10 which removed the `itertools` dependency. I publish fluent 0.0.1 to creates.io.
