### ISSUE TITLE
Remove unwrap from Resolver

### ISSUE THREAD

**Issue by zbraniecki** [projectfluent/fluent-rs#80]
Resolver code uses some `unwrap` which should be replaced with error handling.

**Comment by zbraniecki** [comment]
I cleaned up examples to use `expect` rather than `unwrap` which I think is way more meaningful.

What's left are:

* unwraps on `FluentValue::as_number`
* unwrap inside of a resolver for CallExpression in `arg.value.to_value(env).unwrap()`

@stasm - thoughts on how we should handle them?

**Comment by stasm** [comment]
Thanks for summarizing what remains to be done here. I opened #86 with proposed fixes.
