### ISSUE TITLE
parse_fixtures_compare test fails on Windows due to different line endings

### ISSUE THREAD

**Issue by msujaws** [projectfluent/fluent-rs#83]
Jared Wein@LAPTOP-BRR0AH2E ~/Documents/GitHub/fluent-rs/fluent-syntax
$ cargo build
    Updating crates.io index
   Compiling fluent-syntax v0.1.1 (C:\Users\Jared Wein\Documents\GitHub\fluent-rs\fluent-syntax)
    Finished dev [unoptimized + debuginfo] target(s) in 17.25s

Jared Wein@LAPTOP-BRR0AH2E ~/Documents/GitHub/fluent-rs/fluent-syntax
$ cargo test
  Downloaded glob v0.2.11
  Downloaded criterion v0.2.9
  Downloaded serde_json v1.0.37
  Downloaded assert-json-diff v0.2.1
  Downloaded rand_xoshiro v0.1.0
  Downloaded atty v0.2.11
  Downloaded csv v1.0.5
  Downloaded itertools v0.8.0
  Downloaded rayon v1.0.3
  Downloaded serde_derive v1.0.85
  Downloaded serde v1.0.85
  Downloaded rand_core v0.3.1
  Downloaded walkdir v2.2.7
  Downloaded cast v0.2.2
  Downloaded criterion-plot v0.3.0
  Downloaded clap v2.32.0
  Downloaded lazy_static v1.2.0
  Downloaded tinytemplate v1.0.1
  Downloaded byteorder v1.3.1
  Downloaded rand_core v0.4.0
  Downloaded rayon-core v1.4.1
  Downloaded rand_os v0.1.1
  Downloaded bitflags v1.0.4
  Downloaded winapi-util v0.1.1
  Downloaded unicode-width v0.1.5
  Downloaded quote v0.6.11
  Downloaded either v1.5.0
  Downloaded num-traits v0.2.6
  Downloaded winapi v0.3.6
  Downloaded textwrap v0.10.0
  Downloaded same-file v1.0.4
  Downloaded itoa v0.4.3
  Downloaded crossbeam-deque v0.2.0
  Downloaded proc-macro2 v0.4.26
  Downloaded ryu v0.2.7
  Downloaded csv-core v0.1.5
  Downloaded libc v0.2.48
  Downloaded crossbeam-utils v0.2.2
  Downloaded crossbeam-epoch v0.3.1
  Downloaded unicode-xid v0.1.0
  Downloaded memchr v2.1.3
  Downloaded cfg-if v0.1.6
  Downloaded scopeguard v0.3.3
  Downloaded memoffset v0.2.1
  Downloaded nodrop v0.1.13
  Downloaded arrayvec v0.4.10
  Downloaded syn v0.15.26
  Downloaded num_cpus v1.9.0
   Compiling arrayvec v0.4.10
   Compiling winapi v0.3.6
   Compiling nodrop v0.1.13
   Compiling libc v0.2.48
   Compiling proc-macro2 v0.4.26
   Compiling cfg-if v0.1.6
   Compiling memoffset v0.2.1
   Compiling lazy_static v1.2.0
   Compiling memchr v2.1.3
   Compiling ryu v0.2.7
   Compiling unicode-xid v0.1.0
   Compiling serde v1.0.85
   Compiling scopeguard v0.3.3
   Compiling rayon-core v1.4.1
   Compiling byteorder v1.3.1
   Compiling unicode-width v0.1.5
   Compiling num-traits v0.2.6
   Compiling rayon v1.0.3
   Compiling itoa v0.4.3
   Compiling either v1.5.0
   Compiling rand_core v0.4.0
   Compiling cast v0.2.2
   Compiling bitflags v1.0.4
   Compiling glob v0.2.11
   Compiling crossbeam-utils v0.2.2
   Compiling textwrap v0.10.0
   Compiling itertools v0.8.0
   Compiling rand_core v0.3.1
   Compiling num_cpus v1.9.0
   Compiling clap v2.32.0
   Compiling crossbeam-epoch v0.3.1
   Compiling quote v0.6.11
   Compiling rand_xoshiro v0.1.0
   Compiling criterion-plot v0.3.0
   Compiling csv-core v0.1.5
   Compiling syn v0.15.26
   Compiling crossbeam-deque v0.2.0
   Compiling winapi-util v0.1.1
   Compiling atty v0.2.11
   Compiling rand_os v0.1.1
   Compiling same-file v1.0.4
   Compiling serde_derive v1.0.85
   Compiling walkdir v2.2.7
   Compiling serde_json v1.0.37
   Compiling csv v1.0.5
   Compiling tinytemplate v1.0.1
   Compiling assert-json-diff v0.2.1
   Compiling criterion v0.2.9
   Compiling fluent-syntax v0.1.1 (C:\Users\Jared Wein\Documents\GitHub\fluent-rs\fluent-syntax)
    Finished dev [unoptimized + debuginfo] target(s) in 46.62s
     Running c:\Users\Jared Wein\Documents\GitHub\fluent-rs\target\debug\deps\fluent_syntax-50e75f5cdb1124cd.exe

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running c:\Users\Jared Wein\Documents\GitHub\fluent-rs\target\debug\deps\parser_fixtures-cf1c70fdc28839b7.exe

running 2 tests
test parse_fixtures_compare ... FAILED
test parse_fixtures ... ok

failures:

---- parse_fixtures_compare stdout ----
Parsing: "tests\\fixtures\\any_char.ftl"
Parsing: "tests\\fixtures\\astral.ftl"
thread 'parse_fixtures_compare' panicked at '

json atoms at path ".body[8].content" are not equal:
    expected:
        "err-😂 = Value\n\n"
    actual:
        "err-😂 = Value\r\n\r\n"

json atoms at path ".body[10].content" are not equal:
    expected:
        "err-invalid-expression = { 😂 }\n\n"
    actual:
        "err-invalid-expression = { 😂 }\r\n\r\n"

json atoms at path ".body[12].content" are not equal:
    expected:
        "err-invalid-variant-key = { $sel ->\n    *[😂] Value\n}\n"
    actual:
        "err-invalid-variant-key = { $sel ->\r\n    *[😂] Value\r\n}\r\n"

', fluent-syntax\tests\parser_fixtures.rs:17:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

failures:
    parse_fixtures_compare

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test parser_fixtures'

Jared Wein@LAPTOP-BRR0AH2E ~/Documents/GitHub/fluent-rs/fluent-syntax
$

**Comment by zbraniecki** [comment]
hmm, interesting. `astral.ftl` has no `\r` in it. Is there a chance that your git client adds `\r`? The fixtures are sensitive to that.

**Comment by Pike** [comment]
The js and python fixtures have a https://github.com/projectfluent/python-fluent/blob/master/.gitattributes to keep those.

**Comment by zbraniecki** [comment]
I read about `.gitattributes`, but it feels to me like it should not be enough. My logic is - the file specifies 3 test files to apply specific line endings onto.

But the problem Jared has is that on Windows git convered a *different* test file to use CRLF.

So, if I'm not mistaken what we really want here is to:

* use .gitattributes to set LF line endings for the whole `./fluent-syntax/tests/fixtures` directory
* override it for the three files in question

Does it sound reasonable?

**Comment by zbraniecki** [comment]
I'm following https://help.github.com/articles/dealing-with-line-endings/

**Comment by zbraniecki** [comment]
I'm not suggesting fixing the fixtures. I'm suggesting adding `.gitattributes` that specify that the fixtures use LF so that Windows git doesn't override it.

**Comment by Pike** [comment]
So, we're not running tests on Windows at all.

And I have this faint idea that we're not normalizing newlines in Junk. @stasm ? If that's true, we need a pattern to ensure that tests pass on Windows.

I'm not sure that .gitattributes is the actual answer, or, at least all of the answer. In the end, we cannot expect that everybody on the planet is going to add their fluent files to .gitattributes, and it's not what our intent was about our newlines decision to keep supporting `\r\n`

**Comment by zbraniecki** [comment]
> In the end, we cannot expect that everybody on the planet is going to add their fluent files to .gitattributes, and it's not what our intent was about our newlines decision to keep supporting \r\n

If I understand the problem scope correctly, we don't need people to add their fluent files to any .gitattributes.
We only need to ensure correct line endings in files we test against the expected JSON AST, which means fixtures.

fluent-rs will happily parse a file with `\r\n`, or with `\n`, but will produce two *slightly* different ASTs that preserve this difference (in Junk in particular).

**Comment by Pike** [comment]
The problem that causes is that outside of Junk, tests are supposed to check for normalized line endings, and they wouldn't if we disable that git feature all over our tests.

**Comment by stasm** [comment]
@zbraniecki's suggestion in https://github.com/projectfluent/fluent-rs/issues/83#issuecomment-457948623 is the right course of action. We should use `.gitattributes` to define how all `*.ftl` files are stored by git. We should do this for all our repositories.

Fluent normalizes line endings of correctly parsed content to `LF`. If there are not syntax errors, all files regardless of their line endings are parsed into an AST in which the line endings inside of `TextElements` are normalized to `LF`.

This isn't true for `Junk`, however. In Syntax 0.8, we changed `Junk` to preserve exactly the characters of the unparsed content. If the file uses `CRLF`, the `Junk` content will have the `CRLF` as well.

Git can be [configured to normalize line endings on commit and on checkout](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_code_core_autocrlf_code). I have this option set to `core.autocrlf = input` globally, so even though I'm on Windows, my checkouts always use `LF` (unless overridden on a file-by-file basis in `.gitattributes`). That's why I've never seen this error. If I change this setting to `false` or `true`, I can reproduce it.

I don't think it's reasonable to expect everyone cloning our repos to set this option to `input`. We should instead use `.gitattributes` to force git to checkout `.ftl` files with line endings which our tests expect.

**Comment by stasm** [comment]
I fixed this in #85 by adding `*.ftl eol=lf` to the top-level `gitattributes`. I'm not entirely sure, but I _think_ that git applies this setting when it's checking files out. @msujaws, if you `git pull` now, git might not normalize the files which are already in your working copy. You might want to clone the whole repo again, or perhaps check out an old revision and then check out `master` again. Thanks for reporting this issue!
